# Generated by Django 5.1 on 2024-08-27 12:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', null=True)),
                ('email', models.CharField(default='', max_length=2000)),
                ('subject', models.TextField(default='', max_length=1000000)),
                ('phone', models.CharField(default='', max_length=1000)),
                ('message', models.TextField(default='', max_length=1130, null=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
